steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['network', 'create', 'cloudbuild-net']

  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--remote', '--init']

  - name: 'python:3-slim'
    args: ['sh', './create_terc.json.sh']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'osm-teryt-solr', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['run',  '--name',  'my_solr', '-d', '-p', '8983:8983', '-t', 'osm-teryt-solr']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec',  'my_solr', 'wait-for-solr.sh']

  - name: 'gcr.io/osm-vink/clean-docker-builder'
    args: ['/bin/sh', '-c' , 'cat push-teryt-to-solr/terc.json | docker exec -i my_solr post -c teryt -type application/json -d']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['logs', 'my_solr']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['stop', 'my_solr']

  - name:  'gcr.io/cloud-builders/docker'
    args: ['cp', 'security.json', 'my_solr:/opt/mysolrhome']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['commit', 'my_solr', 'gcr.io/osm-vink/osm-teryt-solr:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['rm', 'my_solr']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/osm-vink/osm-teryt-solr:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'osm-teryt-solr',
           '--image=gcr.io/osm-vink/osm-teryt-solr',
           '--region=us-central1',
           '--memory=256Mi',
           '--allow-unauthenticated',
           '--set-env-vars=LOG4J_PROPS=/opt/solr/server/resources/log4j2-console.xml,SOLR_HEAP=250m'
    ]

images: ['gcr.io/osm-vink/osm-teryt-solr:latest']